Repository hmcts/cnp-flux-config, pull requests merged in 2022-11, with the labels that each got.

#18943 CIV-5348 - remove civil prod identity
  k8s/namespaces/admin/flux-helm-operator/rbac/prod-role-binding.yaml
Labels: stale

#18733 NFDIV-3043: added config for cron nfdiv-cron-resend-co-pronounced-cover-letters
  apps/nfdiv/aat/00/kustomization.yaml
  apps/nfdiv/aat/01/kustomization.yaml
  apps/nfdiv/aat/base/kustomization.yaml
  apps/nfdiv/automation/kustomization.yaml
  apps/nfdiv/demo/00/kustomization.yaml
  apps/nfdiv/demo/01/kustomization.yaml
  apps/nfdiv/demo/base/kustomization.yaml
  apps/nfdiv/ithc/00/kustomization.yaml
  apps/nfdiv/ithc/01/kustomization.yaml
  apps/nfdiv/ithc/base/kustomization.yaml
  apps/nfdiv/nfdiv-cron-resend-co-pronounced-cover-letters/aat/00.yaml
  apps/nfdiv/nfdiv-cron-resend-co-pronounced-cover-letters/aat/01.yaml
  apps/nfdiv/nfdiv-cron-resend-co-pronounced-cover-letters/demo/00.yaml
  apps/nfdiv/nfdiv-cron-resend-co-pronounced-cover-letters/demo/01.yaml
  apps/nfdiv/nfdiv-cron-resend-co-pronounced-cover-letters/image-policy.yaml
  apps/nfdiv/nfdiv-cron-resend-co-pronounced-cover-letters/image-repo.yaml
  apps/nfdiv/nfdiv-cron-resend-co-pronounced-cover-letters/ithc/00.yaml
  apps/nfdiv/nfdiv-cron-resend-co-pronounced-cover-letters/ithc/01.yaml
  apps/nfdiv/nfdiv-cron-resend-co-pronounced-cover-letters/nfdiv-cron-resend-co-pronounced-cover-letters.yaml
  apps/nfdiv/nfdiv-cron-resend-co-pronounced-cover-letters/perftest/00.yaml
  apps/nfdiv/nfdiv-cron-resend-co-pronounced-cover-letters/perftest/01.yaml
  apps/nfdiv/perftest/00/kustomization.yaml
  apps/nfdiv/perftest/01/kustomization.yaml
  apps/nfdiv/perftest/base/kustomization.yaml
  apps/nfdiv/preview/base/kustomization.yaml
Labels: stale

#19344 Perftest enable-deletejob
  k8s/namespaces/dm-store/dm-store/perftest.yaml
Labels: do not merge

#19120 DTSPO-10592. ADD aso-rg
  apps/bsp/azure-resourcegroup/resourcegroup.yaml
  apps/bsp/preview/base/kustomization.yaml
Labels: stale

#19436 DEmo-deploy-branch
  apps/em/em-stitching/demo-image-policy.yaml
Labels: do not merge

#19486 Patching flux v2 gotk and image automation config files on ptl
  apps/flux-system/ptl-intsvc/base/kustomization.yaml
Labels: DO-NOT-MERGE
