Repository hmcts/cnp-flux-config, pull requests merged in 2023-12, with the labels that each got.

#27208 Reduce pod count for db switch over
  apps/em/em-anno/aat.yaml
Labels: do not merge

#27091 bulk-scan-processor (demo) to point at PR-3190 allowing pps legal statement branch to be tested
  apps/bsp/bulk-scan-processor/demo.yaml
Labels: DO-NOT-MERGE

#27273 Reduce pod count for db switch over
  apps/em/em-anno/prod.yaml
Labels: DO-NOT-MERGE

#26259 Rwa 2917 workflow api bringback replicas
  apps/wa/wa-workflow-api/prod.yaml
Labels: stale

#26261 Rwa 2917 resume ceh jobs
  apps/wa/wa-case-event-handler-clean-up-messages/prod-00.yaml
  apps/wa/wa-case-event-handler-clean-up-messages/prod-01.yaml
  apps/wa/wa-messages-find-problem-messages/prod-00.yaml
  apps/wa/wa-messages-find-problem-messages/prod-01.yaml
  apps/wa/wa-messages-reset-problem-messages/prod-00.yaml
  apps/wa/wa-messages-reset-timestamp-problem-messages/prod/00.yaml
  apps/wa/wa-messages-reset-timestamp-problem-messages/prod/01.yaml
  apps/wa/wa-messages-set-processed-state-messages/prod/00.yaml
  apps/wa/wa-messages-set-processed-state-messages/prod/01.yaml
Labels: stale
