Repository hmcts/cnp-flux-config, pull requests merged in 2023-11, with the labels that each got.

#25909 AM-3008 Connect to v15 ORM Perftest - v15 password, user and host tak…
  apps/am/am-org-role-mapping-service/perftest.yaml
Labels: stale

#25911 AM-3009 Connect to v15 RABS Pertftest - v15 RAS and JBS password, use…
  apps/am/am-role-assignment-batch-service/perftest-00.yaml
  apps/am/am-role-assignment-batch-service/perftest-01.yaml
Labels: stale

#25913 AM-3010 Connect to v15 RARB Perftest - v15 ORM password, user and hos…
  apps/am/am-role-assignment-refresh-batch/perftest-00.yaml
  apps/am/am-role-assignment-refresh-batch/perftest-01.yaml
Labels: stale

#26300 Updated v15 DB details for Dm-Store on Perftest
  apps/dm-store/dm-store/perftest.yaml
Labels: do not merge

#26358 Shut down Em-Hrs-Api on Perftest
  apps/em/em-hrs-api/perftest.yaml
  apps/em/em-hrs-ingestor/perftest.yaml
Labels: do not merge

#26243 CFCL - Run migration for one case
  apps/et/et-ccd-case-migration/prod-00.yaml
  apps/et/et-ccd-case-migration/prod-01.yaml
Labels: stale

#26240 CFCL - Enable migration
  apps/et/et-ccd-case-migration/prod-00.yaml
  apps/et/et-ccd-case-migration/prod-01.yaml
Labels: stale

#26244 CFCL - Stop migration
  apps/et/et-ccd-case-migration/prod-00.yaml
  apps/et/et-ccd-case-migration/prod-01.yaml
Labels: stale

#26684 Adding plum-batch to sbox and setting tolerations to ensure it only runs on spot instance nodes
  apps/cnp/plum-batch/sbox.yaml
  apps/cnp/plum-frontend/sbox.yaml
  apps/cnp/sbox/base/kustomization.yaml
  docs/app-deployment-v2.md
Labels: do not merge

#26699 Update em-anno health check endpoint on Prod
  apps/xui/xui-webapp/prod.yaml
Labels: do not merge

#26749 Updated cronjob config on Perftest & Aat for em-anno
  apps/em/em-anno/aat.yaml
  apps/em/em-anno/perftest.yaml
Labels: do not merge

#26677 Reduced pod count to zero to complete DB switch over
  apps/dm-store/dm-store/prod.yaml
Labels: do not merge

#26590 Enable JRD eLinks v2 in AAT (to be merged on 20th Nov)
  apps/sptribs/sptribs-case-api/aat.yaml
Labels: stale, DO-NOT-MERGE

#26599 FPET-779: Add LA email domain to allowed list
  apps/adoption/adoption-web/adoption-web.yaml
Labels: stale

#26246 RWA-2917 Suspend CEH related Cron jobs
  apps/wa/wa-case-event-handler-clean-up-messages/prod-00.yaml
  apps/wa/wa-case-event-handler-clean-up-messages/prod-01.yaml
  apps/wa/wa-messages-find-problem-messages/prod-00.yaml
  apps/wa/wa-messages-find-problem-messages/prod-01.yaml
  apps/wa/wa-messages-reset-problem-messages/prod-00.yaml
  apps/wa/wa-messages-reset-timestamp-problem-messages/prod/00.yaml
  apps/wa/wa-messages-reset-timestamp-problem-messages/prod/01.yaml
  apps/wa/wa-messages-set-processed-state-messages/prod/00.yaml
  apps/wa/wa-messages-set-processed-state-messages/prod/01.yaml
Labels: stale

#26248 RWA-2917 Set Replicas to Zero for Workflow API
  apps/wa/wa-workflow-api/prod.yaml
Labels: stale
