Repository hmcts/cnp-flux-config, pull requests merged in 2024-04, with the labels that each got.

#29916 Toggle FR CFV feature flag for prod
  apps/financial-remedy/finrem-cos/prod.yaml
Labels: stale

#30341 Added HPA config for Em-Ccd-Orc
  apps/em/em-ccd-orchestrator/em-ccd-orchestrator.yaml
  apps/em/em-ccd-orchestrator/perftest.yaml
  apps/em/em-ccd-orchestrator/prod.yaml
Labels: DO-NOT-MERGE

#29919 Enable CFV migration task for FR cases
  apps/financial-remedy/finrem-cron-one-off-task/prod/prod.yaml
Labels: stale

#30021 Adding HPA config for ccd-data-store
  apps/ccd/ccd-data-store-api/perftest.yaml
Labels: DO-NOT-MERGE

#30526 Stopping pods for the migration
  apps/ccd/ccd-definition-store-api/prod.yaml
  apps/ccd/ccd-user-profile-api/prod.yaml
  apps/cpo/case-payment-orders-api/prod.yaml
Labels: DO-NOT-MERGE

#30330 SIDM-8234 Decomission idam-web-admin
  apps/idam/aat/base/kustomization.yaml
  apps/idam/automation/kustomization.yaml
  apps/idam/base/kustomization.yaml
  apps/idam/demo/base/kustomization.yaml
  apps/idam/idam-api/aat.yaml
  apps/idam/idam-api/demo.yaml
  apps/idam/idam-api/idam-api.yaml
  apps/idam/idam-api/ithc.yaml
  apps/idam/idam-api/perftest.yaml
  apps/idam/idam-api/preview.yaml
  apps/idam/idam-api/sbox.yaml
  apps/idam/idam-web-admin/aat.yaml
  apps/idam/idam-web-admin/demo.yaml
  apps/idam/idam-web-admin/idam-web-admin.yaml
  apps/idam/idam-web-admin/image-policy.yaml
  apps/idam/idam-web-admin/image-repo.yaml
  apps/idam/idam-web-admin/ithc.yaml
  apps/idam/idam-web-admin/perftest.yaml
  apps/idam/idam-web-admin/preview-image-policy.yaml
  apps/idam/idam-web-admin/preview.yaml
  apps/idam/idam-web-admin/sbox.yaml
  apps/idam/ithc/base/kustomization.yaml
  apps/idam/perftest/base/kustomization.yaml
  apps/idam/preview/base/kustomization.yaml
  apps/idam/sbox/base/kustomization.yaml
Labels: stale

#30724 Update demo image to point to pr-930
  apps/adoption/adoption-cos-api/demo-image-policy.yaml
  apps/adoption/adoption-cos-api/demo.yaml
Labels: enable_keep_helm
