Repository hmcts/cnp-flux-config, pull requests merged in 2024-01, with the labels that each got.

#28302 increase pcq aat resources
  apps/pcq/pcq-frontend/aat.yaml
Labels: stale

#28283 AM-3110 0 Replicas AAT for JBS RAS ORM
  apps/am/am-judicial-booking-service/aat.yaml
  apps/am/am-org-role-mapping-service/aat.yaml
  apps/am/am-role-assignment-batch-service/aat-00.yaml
  apps/am/am-role-assignment-batch-service/aat-01.yaml
  apps/am/am-role-assignment-refresh-batch/aat-00.yaml
  apps/am/am-role-assignment-refresh-batch/aat-01.yaml
  apps/am/am-role-assignment-service/aat.yaml
Labels: stale

#27029 DTSSTCI-84: Enable JRD V2 API in prod
  apps/sptribs/sptribs-case-api/prod.yaml
Labels: DO-NOT-MERGE

#28751 Updated v15 DB config on AAT for em-stitching
  apps/em/em-stitching/aat.yaml
Labels: DO-NOT-MERGE

#25818 Update aat.yaml
  apps/ccd/ccd-data-store-api/aat.yaml
Labels: stale, DO-NOT-MERGE

#28686 FPET-830 and FPET-729 URL's update in cnp-flux
  apps/adoption/adoption-cos-api/prod.yaml
  apps/adoption/adoption-cron-draft-case-deletion-alert/prod.yaml
  apps/adoption/adoption-cron-multi-child-draft-application-alert/prod.yaml
  apps/adoption/adoption-web/prod.yaml
Labels: stale
