Repository hmcts/cnp-flux-config, pull requests merged in 2025-04, with the labels that each got.

#37660 EXUI-2962: changes for prod release
  apps/em/aat/base/kustomization.yaml
  apps/em/base/kustomization.yaml
  apps/em/demo/base/kustomization.yaml
  apps/em/ithc/base/kustomization.yaml
  apps/em/perftest/base/kustomization.yaml
  apps/em/prod/base/kustomization.yaml
Labels: do not merge

#37048 CME-346: Create ithc image policy for am-role-assignment-refresh-batch
  apps/am/am-role-assignment-refresh-batch/ithc-image-policy.yaml
  apps/am/am-role-assignment-refresh-batch/ithc.yaml
  apps/am/automation/kustomization.yaml
Labels: stale

#37155 CME-346 AM ORM in ITHC create refresh job
  apps/am/am-org-role-mapping-service/ithc.yaml
Labels: stale

#38285 PAY-7458 PR-956 payBubble into demoInt
  apps/fees-pay/ccpay-bubble-frontend-int/demo-int-image-policy.yaml
  apps/fees-pay/ccpay-bubble-frontend-int/demo.yaml
Labels: enable_keep_helm
